project init
chingu-voyages/v44-tier3-team-39 pull request #15
Opened 2023-05-09 05:42 UTC by shijiezhou1

Nextjs and Expressjs

2023-05-09 15:09 UTC, gracesuhyun submitted a review, later dismissed

2023-05-09 17:00 UTC, gamadjg requested changes
First comment practice... Let's place the gitignore and readme outside of the client/server folders since it needs to catch that editorconfig file. 

I use this to generate my gitignore files so it covers OS's/editors too:  https://www.toptal.com/developers/gitignore

Other than that everything looks g2g.

2023-05-09 17:01 UTC, gamadjg approved these changes, later dismissed

2023-05-09 22:55 UTC, shijiezhou1 commented
> 

Okay. I updated it

2023-05-10 06:54 UTC, gamadjg approved these changes, later dismissed

2023-05-10 12:32 UTC, merged